export * from './praise/praise.page';
export * from './quote/quote.page';
export * from './song/song.page';
export * from './song-detail/song-detail.page';
export * from './home/home.page';
export * from './praise-eng/praise-eng.page';
export * from './praise-tel/praise-tel.page';
export * from './songs-list/songs-list.page';
export * from './song-detail/PrettyPrint';